const teams = [

  { id: "nit-delhi", name: "NIT Delhi", logo: "assets/logos/nit-delhi.png", pool: "A" },
  { id: "nit-trichy", name: "NIT Tiruchirappalli", logo: "assets/logos/nit-trichy.png", pool: "A" },
  { id: "mnit-jaipur", name: "MNIT Jaipur", logo: "assets/logos/mnit-jaipur.png", pool: "A" },
  { id: "nit-jalandhar", name: "NIT Jalandhar", logo: "assets/logos/nit-jalandhar.png", pool: "A" },
  { id: "nit-hamirpur", name: "NIT Hamirpur", logo: "assets/logos/nit-hamirpur.png", pool: "A" },
  { id: "nit-surathkal", name: "NIT Surathkal", logo: "assets/logos/nit-surathkal.png", pool: "B" },
  { id: "nit-warangal", name: "NIT Warangal", logo: "assets/logos/nit-warangal.png", pool: "B" },
  { id: "nit-calicut", name: "NIT Calicut", logo: "assets/logos/nit-calicut.png", pool: "B" },
  { id: "nit-patna", name: "NIT Patna", logo: "assets/logos/nit-patna.png", pool: "B" },
  { id: "nit-goa", name: "NIT Goa", logo: "assets/logos/nit-goa.png", pool: "B" },
  { id: "nit-agartala", name: "NIT Agartala", logo: "assets/logos/nit-agartala.png", pool: "C" },
  { id: "nit-arunachal", name: "NIT Arunachal Pradesh", logo: "assets/logos/nit-arunachal.png", pool: "C" },
  { id: "nit-meghalaya", name: "NIT Meghalaya", logo: "assets/logos/nit-meghalaya.png", pool: "C" },
  { id: "nit-mizoram", name: "NIT Mizoram", logo: "assets/logos/nit-mizoram.png", pool: "C" },
  { id: "nit-sikkim", name: "NIT Sikkim", logo: "assets/logos/nit-sikkim.png", pool: "C" },
  { id: "nit-raipur", name: "NIT Raipur", logo: "assets/logos/nit-raipur.png", pool: "D" },
  { id: "nit-rourkela", name: "NIT Rourkela", logo: "assets/logos/nit-rourkela.png", pool: "D" },
  { id: "nit-silchar", name: "NIT Silchar", logo: "assets/logos/nit-silchar.png", pool: "D" },
  { id: "nit-srinagar", name: "NIT Srinagar (J&K)", logo: "assets/logos/nit-srinagar.png", pool: "D" },
  { id: "nit-uttarakhand", name: "NIT Uttarakhand", logo: "assets/logos/nit-uttarakhand.png", pool: "D" },
  { id: "svnit-surat", name: "SVNIT Surat", logo: "assets/logos/svnit-surat.png", pool: "E" },
  { id: "nit-puducherry", name: "NIT Puducherry", logo: "assets/logos/nit-puducherry.png", pool: "E" },
  { id: "iiest-shibpur", name: "IIEST Shibpur", logo: "assets/logos/iiest-shibpur.png", pool: "E" },
  { id: "manit-bhopal", name: "MANIT Bhopal", logo: "assets/logos/manit-bhopal.png", pool: "F" },
  { id: "nit-durgapur", name: "NIT Durgapur", logo: "assets/logos/nit-durgapur.png", pool: "F" },
  { id: "nit-jamshedpur", name: "NIT Jamshedpur", logo: "assets/logos/nit-jamshedpur.png", pool: "F" },
  { id: "nit-kurukshetra", name: "NIT Kurukshetra", logo: "assets/logos/nit-kurukshetra.png", pool: "F" },
  { id: "nit-nagaland", name: "NIT Nagaland", logo: "assets/logos/nit-nagaland.png", pool: "F" },
  { id: "vnit-nagpur", name: "VNIT Nagpur", logo: "assets/logos/vnit-nagpur.png", pool: "F" },
  { id: "nit-allahabad", name: "NIT Allahabad (MNNIT)", logo: "assets/logos/nit-allahabad.png", pool: "F" },
    {
  id: "nit-andhra-pradesh",
  name: "NIT Andhra Pradesh",
  logo: "assets/logos/nit-andhra-pradesh.png",
  pool: "E"
}
];
